Un documento è costituito da un insieme di pagine in cui ci si muove
grazie a collegamenti ipertestuali inseriti nel documento stesso o
seguendo frecce. 
I documenti interattivi possono contenere esempi il cui contenuto
cambia se si clicca su opportuni tasti <span class="text_icon doch_reload">$wims_name_doch_reload</span>.
<h2>Navigazione</h2>
La navigazione all'interno di un documento può avvenire
<ul>
    <li>utilizzando i collegamenti ipertestuali presenti nelle pagine
    del documento o nell'indice del documento;</li>
    <li>seguendo un ordine di lettura suggeristo dall'autore grazie a bottoni
        <ul>
            <li><span class="text_icon doch_prev">$wims_name_doch_prev</span> per andare alla pagina precedente,</li>
            <li><span class="text_icon doch_next">$wims_name_doch_next</span> per leggere la pagina successiva,</li>
            <li><span class="text_icon doch_up">$wims_name_doch_up</span> per tornare alla pagina "genitore" della pagina attuale.</li>
        </ul>
    </li>
</ul>
Le pagine del documento che si sono percorso costituiscono la "storia" della lettura: 
ci si può muovere in questa "storia" utilizzando le frecce
<span class="text_icon backhist">&lt;&lt;</span> Cronologia <span class="text_icon nexthist">&gt;&gt;</span>,
che appariranno durante la navigazione.
<h2>Effettuare una ricerca all'interno di un documento</h2>
Per effettuare la ricerca di una parola all'interno del documento, la cosa
migliore è tornare alla prima pagina del documento e cliccare 
    sulla voce del menu  <span class="wims_button icon_button disabled"><span class="doch_printable">$wims_name_doch_printable</span></span>.
