
<h2 class="wimscenter">Formato dell'enunciato</h2>
<p>
È possibile scrivere l'enunciato dell'esercizio in due formati: html o
TeX. Grazie ai progressi della visualizzazione della matematica in
html (si veda più sotto) il formato TeX non è più necesario per una
corretta visualizzazione dei simboli matematici e se ne sconsiglia
vivamente l'uso.
</p><p>
Se l'esercizio non contiene formule matematiche complicate
(per esempio matrici), l'utilizzo del formato html è del tutto
appropriato. La generazione dell'esercizio sarà più rapida
e ci saranno meno problemi di compatibilità, soprattutto
in futuro.
</p><p>
Il formato html è estramente semplice da utilizzare se l'enunciato
dell'esercizio contiene solo semplice testo. Si tratta semplicemente
di assicurarsi di sostituire gli eventuali simboli <span class="tt">&lt;</span>
con il codice <span class="tt">&#38;lt;</span>, per evitare che tale
simbolo sia interpretato come un comando html. Per il resto,
la formattazione html può essere utilizzata, in particolare
per gli indici (<span class="tt">&lt;sub&gt;</span> e <span class="tt">&lt;/sub&gt;</span>) e gli esponenti
(<span class="tt">&lt;sup&gt;</span> e <span class="tt">&lt;/sup&gt;</span>).
</p><p>È anche possibile inserire nell'enunciato collegamenti a siti esterni.
Per esempio, è possibile inserire figure nel testo dell'enunicato
senza aver bisogno di caricare queste figure sul server.
(Sarà sufficiente dare l'indirizzo web esatto di tali figure.)
</p><p>
È possibile inserire nell'esercizio simboli e formule matematiche
!href cmd=help&special_parm=math molto facilmente
 se si utilizza il formato html. Se proprio si verificano problemi di
 visualizzaizone, allora è disponibile il formato TeX.
Per utilizzaro, dovete conoscere la sintassi dei comandi TeX.
</p><p>
Utilizzato il formato html è anche possibile inserire nell'enunciato
!href cmd=help&special_parm=embedans i campi delle risposte
 e
!href cmd=help&special_parm=draw disegni
 generati automaticamente.
</p><p>
Si sottolinea che gli altri elementi degli esercizi (testo risposta,
commenti, suggerimenti e soluzione) accettano solo il formato html.
E che il formato html permette di inserire simboli e formule matematiche
in tali elementi.
</p>
