
<h2>Il formato OEF</h2>
<p>

OEF significa ``online exercise format'', un formato speciale per programmare 
esercizi interattivi per l'insegnamento <em>computer-aided</em>. Lo scopo dell'ideazione
di questo formato è quello di creare uno standard per lo scambio di contenuti
tra sistemi differenti. Per questo il formato è stato ideato in modo da 
contenere solo le informazioni matematiche sugli esercizi.
</p><p>
Il vantaggio del formato OEF è che rende molto facile la creazione di esercizi.
Ma occorre tenere presente che gli esercizi creati in questo modo, in 
particolare quelli creati da $module_title, hanno delle prestazioni inferiori
rispetto a quelli scritti nel linguaggio nativo di WIMS.
!! tolta la seguente: mi sembra obsoleta
!! It is hard to imagine, at least for the time being,
!! the WIMS exercises such as Q-Puzzle, the Coincidence series or again the
!! Shoot series, be transformed into oef format.
</p><p>
È possibile anche consultare gli 
!href cmd=help&special_parm=examples esempi
 per avere un'idea della struttura di un file OEF.
 </p>
<h3>Sintassi</h3>
<p>Il formato OEF è molto simile al formato LaTeX. È costituito da comandi
seguiti da uno o più parametri. Un comando è una parola
preceduta dal carattere <span class="tt wims_code_words">\</span>,
e i parametri sono inclusi in parentesi graffe.
Per esempio, nell'istruzione seguente
</p>
<pre>
   \answer{La risposta è}{1; sì,no}{type=radio}
</pre>
il comando è <span class="tt wims_code_words">answer</span>, 
che ammette 3 parametri: <span class="tt wims_code_words">La risposta è</span>, <span class="tt wims_code_words">1; sì,no</span>
e <span class="tt wims_code_words">type=radio</span>.
Nell'istruzione
<pre>
   \choice{La risposta è}{sì}{no}
</pre>
il comando è <span class="tt wims_code_words">choice</span>,
che ammette 3 parametri: <span class="tt wims_code_words">La risposta è</span>, <span class="tt wims_code_words">sì</span>
e <span class="tt wims_code_words">no</span>.


<h3>Elenco dei comandi</h3>
<p>Qui di seguito un breve elenco dei principali comandi per esercizi OEF riconosciuti da WIMS.
Si vedano anche le
!href cmd=help&special_parm=parameters istruzioni sui parametri
 per la sintassi dei vari parametri utilizzabili.
 </p>

