!if $wims_read_parm!=$empty
  !set err_=!word 1 of $wims_read_parm
  !set comp_=!word 2 to -1 of $wims_read_parm
!else
  !set err_=!word 1 of $error
  !set comp_=!word 2 to -1 of $error
!endif
!set wims_module_log=error: $err_
!if $err_ iswordof nouser usernotintchat adressplay workinprogress badright disconnected toomuchliving goodsave notallowedmodule notopen toobigfile badfilename
  !changeto lang/msg.phtml.$lang
!else
  !set module_language=$lang
  !msg $err_
!endif
