<h2>Importer des ressources d'une classe voisine</h2>
<p>
Vous pouvez importer des ressources ou comptes de participants d'une
!href cmd=help&special_parm=neighbor classe voisine
 effective pour enseignant.
</p><p>
Pour importer à partir d'une classe, choisissez le nom de la classe
dans la liste des autres classes. Si vous avez la permission d'en importer,
un lien va vous conduire à une page vous donnant la liste de ressources importables.
Seules les ressources que vous n'avez pas dans votre propre classe seront listées.
</p><p>
L'importation d'une ressource n'affecte pas cette ressource dans la classe qui
exporte. Si vous modifiez la ressource importée dans votre classe, son originale
dans la classe qui exporte ne sera pas modifiée, et vice versa. Si vous
voulez partager les modifications avec d'autres classes, envisagez d'utiliser
!href cmd=help&special_parm=share le partage de ressources
 avec elles.
</p><p>
En ce qui concerne les feuilles d'exercices et d'examen, seules les feuilles
actives (ou périmées) sont importables. Une fois installées dans votre
classe, les feuilles importées deviendront inactives. Ceci vous permettra de
vérifier le matériel importé, éventuellement de le modifier, avant de l'activer.
</p><p>
En ce qui concerne les comptes des participants, notez que vous ne pouvez
importer un participant si le nom de login est en utilisation dans votre
classe (par la même personne ou par une autre) même si vous avez effacé ce
dernier.
</p>
