<h2>Classes voisines</h2>
<p>
Des relations de voisinage entre classes virtuelles sur un même site WIMS
peuvent être établies. Deux classes peuvent devenir voisines quand
l'enseignant de chacune a
!href cmd=help&special_parm=neibordecl déclaré
 l'autre comme sa classe voisine. Les ressources d'enseignement (documents,
exercices, feuilles) ainsi que les informations de participants peuvent être
!href cmd=help&special_parm=import échangées
 ou
!href cmd=help&special_parm=share partagées
 entre classes voisines et les participants ayant des comptes identiques dans
des classes voisines peuvent aller de l'une dans l'autre sans retaper leurs
mots de passe. Une classe peut avoir autant de voisins qu'elle le veut.
</p><p>
Les relations de voisinage entre deux classes existent avec plusieurs
objectifs&nbsp;: pour enseignant, pour participants ou pour les deux.
</p><ul><li>
Une relation de voisinage pour enseignant permet l'échange et/ou le partage
de ressources entre les deux classes (y compris les comptes de participant).
</li><li>
Une relation de voisinage pour participants permet le changement de classe direct 
des participants d'une classe à l'autre pour les participants ayant un compte
dans chacune des classes (même identifiant et même mot de passe).
Il leur suffit d'utiliser le lien "autres classes" de la page d'accueil.
</li></ul><p>
Quelques exemples typiques de groupement de classes voisines se trouvent
!href cmd=help&special_parm=neiexample ici
.
</p>
