
<b>"Buur klassen"</b>.
<p>
"Buur relaties" tussen klassen op de zelfde server zijn mogelijk.
Twee klassen worden "buurklassen" wanneer de supervisors van beide klassen
!href cmd=help&special_parm=neibordecl elkaar erkend
 hebben als "buren".
 Lesmateriaal (documenten,werkbladen,oefeningen) als ook leerling informatie
 kan worden
!href cmd=help&special_parm=import uitgewisseld
 of
!href cmd=help&special_parm=share gedeeld
Leerlingen met een acount in buurklassen kunnen ongemerkt van de ene klas naar de andere
(dus zonder uit te loggen).
<br>
Een klas kan een onbeperkt aantal buurklassen hebben.
</p><p>
Les relations de voisinage entre deux classes existent avec plusieurs
objectifs&nbsp;: pour enseignant, pour participants ou pour les deux.
</p><ul><li>
Une relation de voisinage pour enseignant permet l'échange et/ou le partage
de ressources entre les deux classes (y compris les comptes de participant).
</li><li>
Une relation de voisinage pour participants permet le changement de classe direct
des participants d'une classe à l'autre pour les participants ayant un compte
dans chacune des classes (même identifiant et même mot de passe).
Il leur suffit d'utiliser le lien "autres classes" de la page d'accueil.
</li></ul><p>
Enkele voorbeelden van buurklas configuraties
!href cmd=help&special_parm=neiexample staan hier
.
</p>
