 <b>Auto.</b> (nom: <span class="tt
 wims_code_words">default</span>)<br> Le logiciel tente de déterminer
 le type de la réponse suivant la bonne réponse donnée.
 Cette capacité
 de détermination automatique est assez limitée et ne peut en tout cas
 pas distinguer d'autres types que fonctions
 numériques/nombres/équations/textes. Même dans ces cas, des
 bizarreries peuvent se produire (le mot anglais "cosy" est interprété
 comme "cos(y)" et le mot français "expie" comme "exp(i*e)"). Donc si
 possible, il est préférable de préciser le type.
