<b>Finite set (literal, formal and approximative).</b>
 (names: <span class="tt">set</span>, <span class="tt">fset</span> and <span class="tt">aset</span>) <br>
 This is a list of (literal) elements separated by commas,
 where the order is not important.
<p>
  If <span class="tt">repeat</span> is a word of option, the elements
  must be with repetition as in the correct answer. Otherwise, the answer is only
  partially correct.
</p><p>
  Si le mot <span class="tt wims_code_words">nospace</span>
  est présent dans l'option, les espaces à l'intérieur des items ne sont
  pas pris en compte.
</p><p>
  For <span class="tt">set</span>, no evaluation is done to the elements (so that 2 and 1+1
  are not the same element).
</p><p>
  For <span class="tt">fset</span>, the elements are evaluated as
  <em>formal expressions</em>.
</p><p>
  For <span class="tt">aset</span>, the elements are evaluated as
  <em>approximative expressions</em>.
</p>
