 <b>Vector.</b> (name: <span class="tt">vector</span>)<br>
 Each coefficient is evaluated and compared to the corresponding coefficient
 of the correct answer. Therefore only numerical vectors can be used here.
 The comparison is done as in the numeric type, coefficient by coefficient
 (option absolute, depends on the precision defined by the author.

 The answer as well as the correct answer can either have or not have
 enclosing pairs of parentheses.

<br>
:option:vector_left=" "
Description de <span class="tt wims_code_words">option</span> :
<p>The option <span class="tt wims_code_words">vector_left</span> and
<span class="tt wims_code_words">vector_right</span> allow for the
choice of the delimeters to be displayed, both in the input field and
in the answer analysis.
</p>
Example
<pre>
\answer{}{\rep}{type=vector}{option=vector_left=\(\lbracket\),vector_right=\(\rbracket\)}
</pre>
<pre>
\answer{}{\rep}{type=vector}{option=vector_left=\(\Bigg\lbrace\),vector_right=&amp;nbsp;}
</pre>
