
<h2>Neighboring classes</h2>
<p>
Neighborhood relations among virtual classes on a same site can be
established. Two classes will become neighbors when supervisors of both have
!href cmd=help&special_parm=neibordecl declared
 the other as their neighbors. Teaching materials (documents,
exercises, worksheets) as well participant information can be
!href cmd=help&special_parm=import exchanged
 or
!href cmd=help&special_parm=share shared
 between neighboring classes, and participants having identical accounts in
neighboring classes can travel from one to the other without retyping their
passwords. A class can have as many neighbors as it likes.
</p><p>
Neighboring relations can be established between two classes with different
objectives: for supervisors, for participants, or both.
</p><ul><li>
Una relazione di vicinato "per il docente" permette lo scambio/condivisione di materiali
tra le due classi (compresi gli account degli studenti).
</li><li>
Una relazione di vicinato "per gli studenti" permette il passaggio diretto
da un corso all'altro per gli studenti che hanno un account in entrambi
i corsi (stesso username e stessa password).
Per passare da un corso all'altor è sufficiente utilizzare il link "Altri corsi" nella home page del corso.
</p><p>
Some examples of typical setup of neighboring class clusters can be found
!href cmd=help&special_parm=neiexample here
.
</p>
