
!read adm/title.phtml 1\
\
Format per full de càlcul

csv (valors separats per comes) i tsv (valors separats per tabuladors) són els formats
de text per a dades de fulls de càlcul. La majoria dels fulls de càlcul
les reconeixen.
!! <p>
!! ods és el format de full de càlcul definit per l'estàndard ISO OpenDocument. Amb el suport de LibreOffice i OpenOffice, és compatible amb qualsevol programa de full de càlcul just.
!! </p>
