:signification
het maken van een tooltip : de eerste parameter is de tekst van de link,
de derde parameter is de tekst zichtbaar in de tooltip,
de tweede parameter is the css style (in a simple form) and/or the position.

:example
<textarea id="wims_show91" cols="100" rows="8" readonly="readonly">
\special{tooltip passer la souris ici,,le mot a 5 lettres}
\special{tooltip passer la souris ici,style="width:100px" class="left", le mot a 5 lettres}
\special{tooltip passer la souris ici,style="width:300px;background-color:blue;color:white",
  une formule \(\frac{a}{b}\)}
</textarea>

