!set wims_module_error=error: $error
!if $oldpenalty<$penalty
  !set penaltymsg=Recibirá una penalización por este grave error.
  !set oldpenalty=$penalty
!endif

<b>$wims_name_Error</b>

!set n=!wordcnt $error
!if $n>1
  $error
  !exit
!endif

!if $error iswordof bad_data bad_reply \
    bad_answer bad_exo nofloat unjustified check_fail no_object\
    bad_step illegal_method bad_method bad_env fixedgoal msg\
    unknown_variable
  !goto $error
!else
  !msg $error
  !exit
!endif

:bad_data
Ha ingresado datos incomprensibles o fuera de contexto.
¿Error de captura?
!exit

:bad_reply
¡No! Tu respuesta es incorrecta. Intentar otra vez.
!exit

:unknown_variable
 La variable <b><em>$unknown</em></b> no está definida aquí.
!exit

:nofloat
 Los números en forma decimal no están permitidos en este ejercicio. ¡Escribe 1/3
 en lugar de 0.33333 y 1/4 en lugar de 0.25!
!exit

:unjustified
Lo sentimos, pero este método no acepta su entrada sin
 justificación adicional. Debes hacerlo de otra forma.
 !exit

:check_fail
Error de software: informe el error.
!exit

:no_object
No tienes nada en este momento para aplicar el método.
 <span class="oef_indbad">$badmeth</span>.
!exit

:bad_step
Quería ir a un paso inválido. 
¿Mal manejo de su parte?
!exit

:illegal_method
 Querías usar un método no autorizado.
 ¿Intento de fraude?
!exit

:bad_method
El método no existe. Probablemente sea un error de práctica.
 Debe ponerse en contacto con su autor para corregirlo.
!exit

:bad_env
Este método es incompatible con el entorno de ejercicio.
!exit

:fixedgoal
Este ejercicio no le permite cambiar la meta.
 Entonces no puedes aplicar este método.
!exit

:msg
 $msg
!exit

:bad_answer
Su respuesta
<div class="wimscenter">
 <b>$bad_name</b> = <span class="tt">$bad_value</span> </div>
!if unknownword iswordof $test
  !set w=!word 3 of $test
  no se entiende: la palabra
  <span class="oef_indbad">$w</span>
  en la respuesta no está relacionado con este problema. Corrija por favor.
  !exit
!endif
!if nocompute iswordof $test
  no esta permitido. Por favor, haga el cálculo usted mismo y
  presentar el valor resultante.
  !exit
!endif
!if badform iswordof $test
  no está escrito correctamente. Por favor, reescríbelo correctamente.
  !exit
!endif
!if notunit iswordof $test
  es solo un numero
  Especifique la unidad en su respuesta.
  !exit
!endif
 no es entendible Corrija el error y vuelva a enviar la respuesta.
!exit

:bad_exo
 Debido a un error en este ejercicio, es imposible analizar
 su respuesta. La única solución para ti es cambiar de ejercicio;
 todas nuestras disculpas.
 <p>
 Veuillez
!if $email!=$empty
  !mailurl $email contactar al autor
!else
  contactar al autor
!endif
ejercicio si desea reportar este error.
</p>
!exit
