<b>Frase composta con elementi dati.</b>
(nome: <span class="tt wims_code_words">compose</span>)

<p>
Gli elementi dati possono essere testuali (parole o gruppi di parole),
formule (formattate con \(...)), o immagini. Devono essere inseriti in
liste che saranno dati come risposta corretta. Eventuali elementi inutili
possono essere aggiunti con la risposta utilizzando un punto e virgola `;'.
</p><p>
 Nella risposta corretta si possono definire sinonimi. Per farlo, i
 sinonimi devono essere aggiunti dopo la risposta corretta principale,
 separati con una barra verticale `|'. Può essere definito un numero arbitrario
 di sinonimi. In questo caso, solo il primo sinonimo (prima della prima `|')
 è costituito da una lista di elementi separati da virgole. Le parole
 che non appaiono nel primo sinonimo non saranno presentati, a meno che non
 siano aggiunti dopo un segno di due punti `:'.
 </p><p>
 Si può indicare con una opzione il separatore che apparirà tra i testi:
 linkword="mot de liaison". Di default è uno spazio.
</p><p>
Basato su DynAPI, potrebbe non funzionare con alcuni browser.
</p>

