 <b>Equazione formale.</b> (nome: <span class="tt wims_code_words">equation</span>)<br>

La risposta deve essere valutata come equazione e il confronto viene effettuato
 per valori compresi in un intervallo definito dall'autore, con la
 precisione definita dall'autore.

 La risposta <span class="tt">a = 0</span> viene considerata equivalente alla risposta <span class="tt">a</span>. Con l'opzione
 <span class="tt wims_code_words">eqsign=yes</span> è invece necessario scrivere <span class="tt"> a = 0</span>.

Se la riposta data dallo studente contiene variabili che non sono presenti
nell'equazione data come soluzione corretta, viene richiesto di
correggere la risposta.
Per evitare ciò, è possibile aggiungere una serie di variabili che sono
ammesse.

Esempio:
<pre>
\answer{}{x+2*y=0,x,y,z}
</pre>

