<b>Selezionare una o più celle in una tabella</b>
(nome: <span class="tt wims_code_words">multipleclick</span>)
<br>

Il tipo <span class="tt wims_code_words">multipleclick</span> analizza la cella o le celle
selezionate dallo studente e le confronta con le risposte corrette
definite dal docente.
<br>
La sintassi generale per questo tipo di domande è:
<pre>
\answer{Commento}{numeri_scelte_corrette;elenco_scelte}{type=multipleclick}
</pre>
Le scelte sono inserite in una tabella se questa viene indicata come
secondo parametro del comando
<span class="tt wims_code_words">\embed{}</span>:
<pre>
\statement{
\embed{r1,X x Y
2 x 3
[a,b;1,2,3]}
}
\answer{}{1,2;a,b,c,d,e,f}{type=multipleclick}
</pre>

<ul>
  <li>la prima riga contiene la dimensione della tabella;</li>
  <li>
    la seconda riga è il numero di colonne e di righe: nell'esempio sopra,
    gli oggetti sono disposti in una tabella con 2 colonne e 3 righe;
  </li><li>
    Nella terza riga è possibile aggiungere le intestazioni delle righe e
    delle colonne della tabella, sotto la forma [nomi_colonne;nomi_righe].
    Se le riposte sono corrette, queste intestazioni saranno verdi,
    altrimenti rosse.
  </li><li>
    Il parametro css class per questa tabella è
    <span class="tt wims_code_words">ans_multipleclick</span>.
    Viene anche impostato un parametro id che è
    <span class="tt wims_code_words">ans_multipleclickN</span>
    (dove <span class="tt">N</span> è il numero della domanda).
    È possibile utilizzare class per impostare uno stile generale e
    id per impostare uno stile specifico
    (se sono presenti più riposte di tipo "multipleclick" nello stesso esercizio).<br>
    Come per tutti gli esercizi OEF, questo può essere fatto attraverso un comando <span class="tt wims_code_words">\css{ }</span>.
    Per esempio:
    <pre>
\css{&#60;style>
.ans_multipleclick {margin-left:auto;margin-right:auto;
border: medium solid #393b40;
text-align:center;}
.ans_multipleclick th,.ans_multipleclick td {border: thin solid #393b40;}
&#60;/style>}

\matrix{tabella=1,2,3,4,5,6,7,8
205,252,327,349,412,423,441,472
3700,1240,435,150,43,18,7,2
54,110,198,420,780,1640,3160,5960
310,396,425,480,612,704,830,946
3540,3260,3120,2890,2710,2570,2280,2090
509,925,1348,1678,2087,2506,2898,3323}

\text{tabella_in_riga=semaine,\tabella[1;],Lucas,\tabella[2;],Louis,\tabella[3;],Mathilde,\tabella[4;],Toto,\tabella[5;],Christine,\tabella[6;],Léa,\tabella[7;]}
\text{numeri_scelte_corrette=10,11,12,13,14,15,16,17,18}

\statement{
 \embed{r1,600x400
9 x 7
[a,b,c,d,e,f,g,h,i;1,2,3,4,5,6,7]}
}
\answer{Commento}{\numeri_scelte_corrette;\tabella_in_riga}{type=multipleclick}
</pre>
  </li><li>
    Le opzioni possibili sono:
    <ul>
      !read help/anstype.it/spliteqweight.phtml
    </ul>
  </li>
</ul>
