<p>Le comité de publication des serveurs de publication
demande l'avis d'un rapporteur. Celui-ci donne son avis sur la publication
du module et peut demander des modifications et des améliorations.
Le comité de publication décide alors de la publication
du module si l'avis est positif. Une fois le module publié, il n'y a de
vérification que par les utilisateurs.
</p><p>
Les rapporteurs s'assurent que les exercices tournent correctement
(point bloquant pour la publication du module). Ils vérifient la présentation des
exercices (clarté des énoncés, typographie). Éventuellement, ils proposent des améliorations.
</p>
