!! Le domande possono essere inserite in questo file. Possono essere utilizzate
!! form in html.
!! Qui c'è un esempio di form per una risposta, che può essere modificato come
!! necessario.

!form reply
  <ul>
    <li><label for="x">x = </label><input size="40" id="x" name="x" value="$x"></li>
    <li><label for="y">y = </label><input size="40" id="y" name="y" value="$y"></li>
  </ul>
  <p class="send_answer">
    <input type="submit" value="$wims_name_send">
  </p>

!formend
