
!read Exindex
!set exocnt=!itemcnt $exolist
!set qcnt=8
!if $qcnt>$exocnt
  !set qcnt=$exocnt
!endif
!if $exocnt<1
  Spiacente, questo modulo non contiene esercizi per ora.
  Riprova più tardi
  !exit
!endif
!if $exocnt=1
  Questo modulo al momento contiene un solo esercizio, <b>
  !item 1 of $titlelist
  </b>.
  !set exoo=!item 1 of $exolist
  !href cmd=new&module=$module&exo=$exoo Provalo.
  !exit
!endif
!form new
<fieldset id="intromenu" class="property_fields">
<legend>$wims_name_setup</legend>

<input type="hidden" name="module" value="$module">
<ul class="wims_nopuce">
<li>
<label for="exo">Seleziona lo scenario:</label>
!if $exocnt>6
  !set selsize=6
!else
  !set selsize=$exocnt
!endif
!set wims_formselect_switch=multiple size=$selsize
!set exo=$special_parm
!if $exo!=$empty
  !set exolist=!listuniq $exo,$exolist
  !set exolist=!replace , by , $ in $exolist
  !set dictionary=$module_dir/Extitles
  !set translator_unknown=leave
  !set titlelist=!exec translator $exolist
!endif
!formselect exo list $exolist prompt $titlelist
!set wims_formselect_switch=
</li><li>
  <label for="style">Stile dell'esercizio:</label>
!formselect style list 1,2,3,4 prompt \
 	trovare il primo passaggio non corretto,\
	trovare tutti i passaggi non corretti,\
	analisi passo passo senza giustificazioni,\
	analisi passo passo con giustificazioni
</li><li>
  <label for="level">Livello di difficoltà:</label>
!default level=2
!formselect level from 1 to 5
</li></ul>
</fieldset>
<div class="wimscenter">
<input type="submit" value="$wims_name_work">
</div>
!formend
