!header
!read Exindex
本模块包含关于 ... 的$exototal个练习.

!!put no if you do not want to have automatic related modules
!set related_modules=
!!complete if you want to put something else than the keywords of INDEX
!set keyw=
!!put yes if some exercises have a latex version defined by the
!!command \latex{}
!set latex_exists=
!! to add a chronometer
!!default scoredelay=60,120
!read oef/intromenu.phtml
!tail
