
!readproc adm/docsheet.prep
!read $docdef content
<div class="wimscenter">
!set scorestat=!getscorestatus sheet=$sh
!if $scorestat=yes
  !if $authscoresuspend!=no
    !set wims_ref_class=wims_button
    !if $wims_scorereg!=suspend
      $name_scoreopen
      !href cmd=resume&job=suspend $wims_name_scoreclose2
    !else
      $name_scoreclose
      !href cmd=resume&job=reopen $wims_name_scorereopen
    !endif
  !endif
!endif
</div>

!if $wims_user=supervisor
  <div class="wimscenter">
  !set wims_ref_class=wims_button
  !href module=adm/class/sheet&sheet=$sh $wims_name_sheetmanagement
  !if $sheet_docpage!=yes
    !set d_=!translate / to , in $sheet_docpage
    !distribute items $d_ into d_,b_
    !set wims_ref_class=wims_button
    !href module=adm/doc&job=edit&doc=$d_&block=$b_ $wims_name_Edit
  !endif
  !set wims_ref_class=wims_button
  !href cmd=resume $wims_name_refresh
.
  </div>
!endif

!tail
