!set m_scores=!words2items $percents
!distribute lines $wims_firstname\
$wims_lastname\
$newmsgcnt\
into\
m_firstname,m_lastname,m_newmsgcnt

!! --- in case of use of file of the document in the presentation page
!if $class_homepage!=yes
  !let m_filedir=$wims_ref_name?session=$wims_session&+cmd=getfile&+special_parm=doc
  !let tmp=!replace internal / by , in $class_homepage
  !sh if [ -d $wims_home/log/classes/$wims_class/doc/$(tmp[1])/files ]; then\
         cd $wims_home/$wims_sesdir;\
         mkdir -p getfile;\
         cd getfile;\
         rm -f doc;\
         ln -s $wims_home/log/classes/$wims_class/doc/$(tmp[1])/files doc;\
      fi
!endif

!! ce qui suit peut servir dans un document mis comme page d'accueil
!! doit être redéfini dans public_html/modules/adm/doc/var.proc
!! pour un document de la classe (voir public_html/modules/adm/doc/var.proc)
!set m_today=!char 1 to 8 of $wims_now
!set m_sheets=!recordcnt wimshome/log/classes/$wims_class/sheets/.sheets
!set m_exams=!recordcnt wimshome/log/classes/$wims_class/exams/.exams
!set m_user_login=$wims_user
!set m_user_lastname=$wims_lastname
!set m_user_firstname=$wims_firstname
!set m_class_code=$wims_class
!set m_daymessage=!record 0 of wimshome/log/classes/$wims_class/.motd
!set m_userdaymessage=!record 0 of wimshome/log/classes/$wims_class/motd/$wims_user

!for i=1 to $m_sheets
  !set l_=!record $i of wimshome/log/classes/$wims_class/sheets/.sheets
  !distribute lines $l_ into m_status$i,m_expiration$i,m_title$i,m_desc$i
!next i
!for i=1 to $m_exams
  !set l_=!record $i of wimshome/log/classes/$wims_class/exams/.exams
  !distribute lines $l_ into m_statusE$i,m_expirationE$i,m_titleE$i,m_descE$i
!next i
!let save_trustfile=$wims_trustfile
!let save_writable=$wims_writable
!let save_readable=$wims_readable
!let wims_trustfile=$wims_trustfile primitives/target.phtml primitives.phtml
!let wims_writable=$wims_writable serial prim parm1 parm2 parm3 parm4 parms anchor w gotcnt gotm p add eq sh_ ex_ l_ m_ p_ a_ b_ t_ d_ prompt n i nadd lmod lses lcmd l ll l1 l2
!let wims_readable=$wims_readable wims_read_parm serial prim parm1 parm2 parm3 parm4 parms anchor w gotcnt gotm p add eq sh_ ex_ l_ m_ p_ a_ b_ t_ d_ prompt n i nadd lmod lses lcmd l ll l1 l2

!! ------ TMP bugfix :
!! bugfix some variable value not correctly assigned in presentation sheet and main page of class
!! this is a temporary correctif (need to modify src/OefMsg2wims/msg2wims.c for a definitive correction (change
!! tmp$k variable name to tmp_$k variable to use wims_prefix instead of wims_writable/wims_readable)
!let t=!makelist tmp v for v=0 to 50
!let t=!nospace $t
!let t=!items2words $t
!let wims_writable=$wims_writable tmp $t
!let wims_readable=$wims_readable tmp $t
!! end of TMP bugfix ------------


!read $deffile content
!let wims_trustfile=$save_trustfile
!let wims_writable=$save_writable
!let wims_readable=$save_readable
