
<b>Cliquer sur une image ou un texte</b> (nom : <span class="tt wims_code_words">click</span>)
<br>
:option:shuffle
Le type <span class="tt wims_code_words">click</span> compare l'objet cliqué
par l'utilisateur avec la bonnes réponse définie par l'enseignant.
Il ne peut être utilisé que dans le cas où il n'y a pas d'autres réponses ou choix
car il envoie directement la réponse après le click.
<br>
La syntaxe générale est :
<pre>
\answer{Commentaire}{1;juste1,faux1,faux2}{type=click}
\answer{Commentaire}{1;&#60;img src="\url1" alt="Image bonne">,&#60;img src="\url2" alt="Image erronée">}{type=click}
</pre>
Vous pouvez utiliser l'option <span class="tt wims_code_words">shuffle</span>
 pour changer l'ordre dans lequel les choix sont montrés.
<pre>
\answer{Commentaire}{1;juste1,faux1,faux2}{type=click}{option=shuffle}
\answer{Commentaire}{1;&#60;img src="\url1" alt="Image bonne">,&#60;img src="\url2" alt="Image erronée">}{type=click}{option=shuffle}
</pre>>
Pour mixer les réponses sans l'option shuffle,
on doit réaliser au préalable un petit travail sur les variables :
<pre>
\text{listegraph=&#60;img src="\urlL" alt="Repère en L">,&#60;img src="\urlT" alt="Repère en T inversé">,&#60;img src="\urlCroix" alt="Repère en croix">}
\text{li=shuffle(3)}
\text{listegraphmixe=\listegraph[\li]}
\integer{rep=position(1,\li)}

\answer{}{\rep;\listegraphmixe}{type=click}
</pre>

