!! This file contains error messages. It will be processed
!! whenever the variable `error' is not empty.
!set wims_module_error=error: $error

<span class="wims_warning">$wims_name_Error</span>

!if empty_data iswordof $error
 La risposta è incompleta.
 !exit
!endif

!if bad_data iswordof $error
 Il server non è stato in grado di interpretare la risposta. Errore di battitura?
 !exit
!endif

!if double_reply iswordof $error
 Hai già dato una risposta a questa domanda e ottenuto un
 punteggio. Le ripetizioni sono ignorate (è inutile utilizzare
 il tasto `reload' del browser per correggere la risposta!)
 !exit
!endif

!if bad_answer iswordof $error
 La risposta <p class="wims_center">
 <b>$bad_name</b> = <span class="tt">$bad_value</span> </p>
 !if nocompute isin $test
  non è accettata: occorre svolgere i conti e
  dare solo il risultato finale.
 !else
  non è comprensibile. Correggere e riproporre la risposta.
 !endif
 !exit
!endif

!if bad_exo iswordof $error
 A causa di un errore in questo esercizio (la risposta esatta per 
 <b>$(replyname$i)</b> non è valida), è impossibile analizzare
 l'esattezza della risposta data. Spiacente, ma è necessario cambiare
 esercizio.
 <p>
 Per favore
 !if $email!=$empty
  !mailurl $email contattare direttamente l'autore
 !else
  contattare l'autore
 !endif
 dell'esercizio se si vuole segnalare l'errore.
 !exit
!endif

$error
