Voici sous deux formes la liste des mots clés reconnus par le moteur de
recherche (et donc permettant la complétion). Sélectionnez la version technique
anglaise des mots clés tels qu'ils sont écrits
ici. Les mots (ou groupes de mots) doivent être séparés par une virgule.
Il est inutile de remettre les noms des domaines dans ce champ, ils sont
automatiquement utilisés par le moteur de recherche.

<div class="wims_instruction">
Dans les modules OEF, les mots clés mis dans un des exercices
dans le champ <span class="tt">\keywords{}</span>
sont automatiquement ajoutés dans les mots clés du module.
</div>
