!read adm/title.phtml 2\
Publication d'un module

Si vous avez un compte dans le centre de publication de modules
que vous avez choisi, vous pouvez demander à publier votre module
ou s'il est déjà publié, en faire des mises à jour.
<p>
Cette publication va se propager automatiquement à travers
les miroirs et les mises à jour automatiques à tous les serveurs WIMS
qui se mettent à jour sur ce serveur de publication.
</p><p>
Donc vous devez faire très attention de ne publier que des modules bien testés.
C'est particulièrement le cas quand vous modifiez un module d'exercices
existant.
</p>
<h3>Cas d'un nouveau module</h3>
!read help/fr/publ_rule.phtml
<h3>Cas de la mise à jour du module</h3>
!!Nous avons tous un désir constant d'améliorer nos oeuvres : une présentation
!!encore plus jolie, encore plus de capacités (ou dans le cas d'un exercice,
!!plus de cas), une réorganisation du code, etc.
!!
<p>
N'oubliez pas de PENSER AUX GENS QUI UTILISENT VOS EXERCICES.
Vous ne devez pas changer le nom des fichiers des exercices&nbsp;: votre
module est peut-être déjà inséré dans des feuilles d'exercices actives ou/et
des examens importants. Vos nouveautés apportent alors des changements au
milieu du travail des gens. Les nouvelles capacités ou présentations
peuvent troubler les élèves ; au pire, un examen important peut être
cassé par un bogue.
</p>
!!<p>En règle générale, vous devez vous abstenir d'introduire des modifications
!!esthétiques ou des renforcements au milieu d'une année académique sur les
!!modules activement utilisés. Seules les corrections de bogues doivent être
!!publiées pendant cette période. Développez vos nouveautés dans une version
!!de développement (sous une adresse test ou dans un compte de développement
!!pour cet effet) et ne les publiez que pendant les vacances scolaires.
!!</p><p>
!!Pour vos utilisations personnelles ou celles de vos élèves, il vous suffit
!!de pointer vos feuilles ou examens sur le module de votre espace de
!!développement. C'est d'ailleurs un bon moyen de faire tester les modules
!!avant la publication.
!!</p><p>
!!Dans tous les cas, sachez que vous pouvez
!!seulement modifier ceux sur lesquels vous avez des droits.
!!Si vous voulez ajouter un
!!NOUVEAU module, votre compte doit en avoir le droit.
!!</p>
