
<h2>Liste des vérifications avant publication</h2>
<h3>Contenu du module</h3>
<ul><li>
  Il n'existe pas de module susceptible d'accueillir mes exercices.
</li><li>
  Les exercices ont été testés en profondeur (tous les scénarios, toutes les données).
</li><li>
  Les exercices peuvent être utilisés en dehors du contexte de ma classe
  (consignes indépendantes de la classe, vocabulaire précis,
  éventuellement prévoir des indications).
</li><li>
  Les exercices présentent un caractère aléatoire suffisant.
    Si certains exercices ont peu d'aléatoire, expliquer dans le fichier NEWS
    l'intérêt de l'exercice. Prévoir une description pour les enseignants
    dans l'exercice lui-même (balise \description).
</li><li>
    La langue a été vérifiée (orthographe, grammaire...)
</li><li>
    Le code html des exercices a été vérifié.
</li><li>
    Les styles css WIMS par défaut ont été utilisés.
</li><li>
    Il est possible de mettre des mots-clés dans le champ
    <span class="tt">keywords</span> d'un exercice du module.
    Les écrire toujours de la même façon.
</li><li>
    Le code des exercices est commenté pour permettre la reprise par un tiers.
</li><li>
    Les noms des fichiers sont constitués d'un unique <b>court</b> terme
    en minuscules avec ou sans chiffres et ne contiennent pas de caractères
    accentués ou spéciaux.
    Exemple : signes.oef ou coordination2.oef
</li></ul>
<h3>Fichiers de configuration</h3>
<ul><li>
  le fichier <span class="tt">intro.phtml</span> a été complété.
</li><li>
  Le fichier <span class="tt">NEWS</span> est à jour.
</li></ul>
<h3>Propriétés du module</h3>
    Les mots-clés du module sont présents et ont été choisis
      dans la liste fournie si possible ou une demande d'ajout de mots-clés a été faite.
      Ces mots-clés permettent d'afficher votre module dans l'arborescence
      du site (recherche par sujet).
