
!read adm/title.phtml 1\
\
Enviar los datos de una hoja de cálculo a la clase

<p>
Para enviar los datos de su hoja de cálculo a la clase guarde los datos en
un fichero en formato de texto (txt, csv o tsv) y después suba el fichero
al servidor.
</p><p>
También puede enviar así informaciones sobre los participantes o las notas.
Para enviar las informaciones en el momento de la inscripción por ejemplo
no debe aparecer ninguna puntuación entre los datos.
</p><p>
Si le añade puntuaciones a la clase la columna correspondiente a estas notas
debe ya existir en la clase. En caso contrario deberá crearla antes de enviar
las notas.
</p><p>
Varias opciones son posibles según si usted usa la autentificación de WIMS
o una autentificación vía un ldap.
</p>
<h3>Caso de autentificación vía WIMS</h3>
La primera línea de la hoja debe estar formada por los nombres de cada columna
(por ejemplo, <span class="tt wims_code_words">login</span>, <span class="tt wims_code_words">firstname</span>, ...). Los nombres
de columna válidos y su significado aparecen en la tabla de abajo.
Puede elegir una combinación arbitraria de estas columnas y colocarlas
en cualquier orden, con la única condición de que el campo <span class="tt wims_code_words">login</span>
debe estar presente obligatoriamente (WIMS utiliza este campo para identificar
a los participantes). Si desea que una línea sea ignorada ponga un carácter <span class="tt wims_code_words">#</span>
en el campo <span class="tt wims_code_words">login</span>.
<p>
Puede utilizar este método para añadir participantes (muchos de una sola vez):
en este caso la hoja de cálculo debe contener suficiente información válida
sobre cada participante que se vaya a añadir (apellidos, nombre, contraseña).
</p><p>
Ejemplo de fichero válido para una inscripción:
</p>
<pre>
login,firstname,lastname,password
menganez,Claudio,Menganez,1234
</pre>

<h3>Caso de autentificación externa</h3>
El formato del fichero es el mismo, pero debe reemplazar el campo
<span class="tt wims_code_words">login</span> por el campo
<span class="tt wims_code_words">external_auth</span> (el campo <span class="tt wims_code_words">login</span>
no debe aparecer).
Debe completar obligatoriamente el apellido y nombre (<span class="tt wims_code_words">lastname</span>,
<span class="tt wims_code_words">firstname</span>) a menos que tenga 
una conexión a un directorio, ldap por ejemplo (declarado en la configuración de la clase).
En ese caso, y solo en ese caso, solo el identificador externo
(<span class="tt wims_code_words">external_auth</span>) debe ser colocado.
Recuerde que es totalmente desaconsejable cambiar el procedimiento de autentificación
una vez que haya participantes registrados.

<p>
Ejemplo de fichero válido para una inscripción:
</p><pre>
external_auth,firstname,lastname
menganez,Claudio,Menganez,1234
</pre>

!read lang/help.$moduclass_lang/fieldtab.phtml
