<h2>Neighboring classes</h2>
<p>
Neighborhood relations among virtual classes on a same site can be
established. Two classes will become neighbors when supervisors of both have
!href cmd=help&special_parm=neibordecl declared
 the other as their neighbors. Teaching materials (documents,
exercises, worksheets) as well participant information can be
!href cmd=help&special_parm=import exchanged
 or
!href cmd=help&special_parm=share shared
 between neighboring classes, and participants having identical accounts in
neighboring classes can travel from one to the other without retyping their
passwords. A class can have as many neighbors as it likes.
</p><p>
Neighboring relations can be established between two classes with different
objectives: for supervisors, for participants, or both.
</p><ul><li>
Une relation de voisinage pour enseignant permet l'échange et/ou le partage
de ressources entre les deux classes (y compris les comptes de participant).
</li><li>
Une relation de voisinage pour participants permet le changement de classe direct
des participants d'une classe à l'autre pour les participants ayant un compte
dans chacune des classes (même identifiant et même mot de passe).
Il leur suffit d'utiliser le lien "autres classes" de la page d'accueil.
</li></ul>
<p>
Some examples of typical setup of neighboring class clusters can be found
!href cmd=help&special_parm=neiexample here
.
</p>
