!! Ponga las preguntas que quiere que se respondan. Habitualmente se hará en
!! un formulario. Es bueno poner un ejemplo con la concepción de la forma
!! de la respuesta.

!form reply
	<ul>
		<li><label for="x">x = </label><input size="40" id="x" name="x" value="$x"></li>
		<li><label for="y">y = </label><input size="40" id="y" name="y" value="$y"></li>
	</ul>
	<p class="send_answer">
	<input type="submit" value="$wims_name_send">
	</p>

!formend
