Qui trovate l'elenco delle parole chiave riconosciute dal motore di ricerca (che
quindi permettendo l'autocompletamento). Per un corretto funzionamento,
utilizzare la versione inglese dei termini tecnici come sono scritti
qui. Parole (o frasi) devono essere separati da una virgola.
È inutile mettere in questo campo le parole utilizzate nel "Campo", in
quanto quelle vengono già utilizzate dal motore di ricerca.

<div class="wims_instruction">
Nei moduli OEF, le parole chiave inserite negli esercizi mediante
il comando <span class="tt">\keywords{}</span>
sono automaticamente aggiunte alle parole chiave del modulo.
</div>
