
<h2>Alcune verifiche prima della pubblicazione</h2>
<h3>Contenuto del modulo</h3>
<ul><li>
  Non sono presenti nella distribuzione altri moduli che potrebbero contenere gli esercizi proposti.
</li><li>
  Gli esercizi sono stati verificati in modo approfondito (tutti gli scenari possibili, tutti i valori dei parametri di configurazione).
</li><li>
  Gli esercizi non fanno riferimento al contesto della mia classe
  (le consegne sono indipendenti dalle convenzioni della mia classe, il
  vocabolario è preciso, altrimenti aggiungete istruzioni specifiche).
</li><li>
  Gli esercizi sfruttano in maniera adeguata la randomizzazione.
    Se alcuni esercizi fanno scarso uso di parametri casuali, spiegate
    nel file NEWS perché possono comunque risultare interessanti. Fornite
    anche una descrizione per gli altri insegnanti nello stesso esercizio
    (ricordate che potete utilizzare il comando
    <span class="tt">\description</span>).
</li><li>
    La lingua è corretta (ortografia, grammatica, ...).
</li><li>
    La correttezza del codice html degli esercizi è stata verificata.
</li><li>
    Viene utilizzato lo stile css standard di WIMS.
</li><li>
    È possibile inserire parole chiave nel campo
    <span class="tt">keywords</span> di ciascun esercizio nel modulo.
    Utilizzando le medesime convenzioni.
</li><li>
    Il codice degli esercizi è sufficientemente commentato per permettere
    l'intervento da parte di terzi.
</li><li>
    I nomi dei file sono termini <b>brevi</b> e scritti in minuscolo, con
    o senza numeri, e non contengono caratteri speciali o lettere accentate.
    Esempio: signes.oef o coordination2.oef
</li></ul>
<h3>File di configurazione</h3>
<ul><li>
  Il file <span class="tt">intro.phtml</span> è stato adattato alle specificità del modulo.
</li><li>
  Il file <span class="tt">NEWS</span> è aggiornato.
</li></ul>
<h3>Proprietà del modulo</h3>
    Sono inserite parole chiave che sono scelte nella lista fornita, se
      possibile, oppure è stato richiesto di aggiungere parole chiave mancanti.
      Queste parole permettono di far apparire correttamente il modulo nella
      struttura ad albero dei risultati della ricerca per argomenti.
