!if $wims_read_parm!=$empty
  !set err_=!word 1 of $wims_read_parm
  !set comp_=!word 2 to -1 of $wims_read_parm
!else
  !set err_=!word 1 of $error
  !set comp_=!word 2 to -1 of $error
!endif
!set wims_module_log=error: $err_
!if $err_ iswordof badsoldate bad_maxfreework badstatutsubject badstatutsolution goodsave goodstatut gooderasefile goodaddfile notnow fwnotperime\
    fwnotactive badfilename gooderase noterasable gooddeactivate notenoughfreespace badstudentfilesize quota_filestudent badallows studentwithoutfw putworknotallow notallowedmodule\
    notallcorrected putworkusernotexists expire_nosoldisplay toomanychar quota_file notallowed_desactivated goodhide addrplay goodarchive notauthsupervisor not_secure alreadyarchivated\
    file_too_large addexo-nofreework not_exo insert_fail no_pick bad_freework too_many_exos already_exist exo-insert exolog-noexo exolog-exoexists exolog-badparameter\
     exolog-nofile exolog-nouser noinlineanswer ok-delexo badscore toomanywimsexo printversion duplicateok truncatedtext geogebratoolong
  !changeto lang/msg.phtml.$lang
!else
  !msg $err_
  $err_
!endif
