!read adm/title.phtml 3\
\
Dependencias de recursos en una clase

<p>
Hay muchas dependencias complicadas entre diferentes tipos de
recursos en un aula virtual.
</p><p>
Por ejemplo, las hojas de examen se definen con referencia a hojas de trabajo, y estas últimas 
pueden utilizar ejercicios de clase. Entonces, si modifica o elimina los últimos, los primeros
 no podrán funcionar correctamente.
</p><p>
Además, las puntuaciones de los participantes se calculan en tiempo real, según el registro de
actividad y los niveles de gravedad de las hojas. Si se cambian 
sus hojas de trabajo activas, las puntuaciones no se pueden
calcular correctamente incluso si el registro de actividad está intacto.
</p>
