<h2>Respalda tu clase </h2>
<p>
Puede descargar una copia de seguridad de la clase como archivo comprimido. 
Si su clase es muy activa, también puede hacer 
copias de seguridad selectivas. El archivo de respaldo puede enviarse más tarde
al servidor para restaurar su clase o copiar algunos recursos 
a una nueva clase.
</p><p>
Todas las fuentes de la clase están escritas en archivos de texto, por lo que 
también puede leerlas y editarlas en su computadora local.
</p><p>
Formatos de archivo comprimido disponibles:
</p><ul><li><span class="wims_code_words">zip</span>
que se puede descomprimir y leer en prácticamente cualquier
sistema (Windows, Mac, Linux / BSD, etc.), pero la compresión no siempre 
es muy eficiente; 
 </li><li><span class="wims_code_words">tgz</span>
se puede leer solo en sistemas similares a 
Unix (Linux, BSD, Sun OS, etc.), pero tiene una tasa de compresión
más elevada;
 </li><li><span class="wims_code_words">tar.gz</span>
que es un sinónimo de <span class="wims_code_words">tgz</span>.
</li></ul>
Por supuesto, WIMS acepta todos los formatos anteriores para su restauración.
