!read adm/title.phtml 3\
\
Actualizar índices
<p>
Esta herramienta está reservada para usuarios expertos que realizan
modificaciones manuales al contenido de la clase. Después de realizar 
estos cambios, puede hacer clic en el enlace correspondiente para actualizar el índice.
</p> <p>
Probablemente necesitará estudiar el código fuente del software para 
obtener detalles sobre cómo modificar manualmente el contenido de la clase.
</p> <p>
No importa si accidentalmente hace clic en uno de los enlaces.
</p>
