
<h2>Declarar una clase vecina</h2>
<p>
La
!href cmd=help&special_parm=neighbor relación de vecindad
entre dos clases es eficaz sólo cuando los profesores de la
dos clases declaran a la otra como su vecina ya sea para el maestro,
ya sea para los participantes o para ambos.
</p> <p>
Aunque en principio, los miembros de una clase vecina no pueden
no modificar su clase (a menos que ellos
!href cmd=help&special_parm=share compartan los recursos
 con nosotros), solo debes declarar otra clase como vecino
si puedes confiar en su maestro.
</p><p>
Al declarar una clase como vecina de un maestro, la permites
!href cmd=help&special_parm=import importar
recursos de su salón de clases. Esto significa que tendrá acceso a
posiblemente datos sensibles de su clase, por ejemplo hojas
o ejercicios ocultos. Asegúrese de que no revelará estos datos a
los alumnos de su clase.
</p><p>
Además, al importar cuentas de participantes de su clase, 
el profesor de su clase vecina tendrá un medio para leer las contraseñas 
personales de sus participantes. (Esto ya es cierto si declara 
a la otra clase como vecina para los participantes). 
Asegúrese de que mantendrá estas contraseñas en secreto.
</p> <p>
Para mantener un alto nivel de seguridad para su clase, 
el principio es declarar las clases vecinas solo cuando sea realmente necesario.
</p>
