<h2> Variables de registro </h2>
<p>
Es posible proporcionar campos adicionales para completar
en el registro (como máximo 10). Para ello, debes dar los nombres que aparecerán
en el formulario de registro (separados por comas).
Estas variables se almacenarán como una variable de registro de participante
con el nombre de <span class="tt"> regprop1 </span>, <span class="tt">regprop2</span>, ...
Puede recuperarlos mediante el enlace de la hoja de cálculo, pero no utilizarlos como filtro.
</p><p>
En el caso de un <span class="tt">$wims_name_create_superclass </span> o un <span class = "tt">$wims_name_create_portal</span>,
las variables son comunes a todas las clases. Sin embargo, solo el administrador de un <span class="tt">$wims_name_create_superclass</span>
o un <span class="tt">$wims_name_create_portal</span> puede crear otros nuevos.
</p><p>
Su número está limitado a $limit_regvars.
</p>
