<h2> Permiso para compartir sus recursos </h2>
<p>
Si permites que la
!href cmd=help&special_parm=neighbor clsse vecina
de
!href cmd=help&special_parm=share comparta
 tus recursos, debes estar consciente del riesgo que eso trae a tu 
 clase.
</p><p>
Uuna vez que haya declarado que un tipo de recurso se puede compartir, la otra clase 
puede compartirlo de manera efectiva. Esto significa que las personas pueden modificar sus recursos, 
incluso dañarlos (al cometer irregularidades).
</p><p>
Es particularmente arriesgado permitir compartir su 
cuenta de maestro. Si otro cambia la contraseña del maestro (o si
hay una intrusión en la otra clase), perderá el acceso a su clase.
</p><p>
Si es posible, es mejor invitar a la otra clase a
!href cmd=help&special_parm=import importar
 tus recursos, en lugar de permitirles compartirlos.
</p><p>
Hay dependencias entre los recursos: compartir algunos te 
obligará a compartir otros (por ejemplo, los exámenes son
dependientes de las hojas de trabajo).
</p><p>
Los cuestionarios no se pueden compartir si alguno de ellos es
un modelo elaborado utilizando variables técnicas.
</p>
