<h2> Detener un recurso compartido </h2>
<p>
Solo clases secundarias en una
!href cmd=help&special_parm=share compartición de recursos
 pueden parar de compartir con 
!href cmd=help&special_parm=neighbor clases vecinas
.</p><p>
Si deja de compartir, su clase saldrá con una copia del
recursos compartidos en el estado actual. Por lo tanto,
detener una acción no tendrá un efecto inmediato en su clase.
La diferencia es que los cambios futuros a estos recursos, ya sea por usted o por
otras clases ya no tendrán repercusiones mutuas.
</p><p>
En algunos casos, si finaliza una relación compartida, será
imposible reiniciar el uso compartido. Si es así, el servidor
dará una advertencia antes de que la operación de dejar de compartir
sea definitiva.
</p>
