<h2> Reinstale una copia de seguridad de la clase </h2>
<p>
Hay principalmente dos ocasiones en las que necesitará reinstalar un 
archivo de respaldo en el servidor.
</p>
<ul><li> <strong>Tu clase está dañada por alguna u 
otra razón. </strong> En este caso, se recomienda una restauración lo más completa posible 
(excepto la configuración del aula y la cuenta del profesor 
si no están dañadas). Debido a las interdependencias de 
los diferentes tipos de recursos en la clase, es posible que una restauración parcial 
no funcione. Y, por supuesto, debes usar
una copia de seguridad de TU clase, pero no la de otra.
</li>
<li> <strong> Quieres instalar los recursos descargados
de otra clase en la tuya. </strong>
Esto solo debe hacerse cuando su clase esté vacía, al comienzo de su 
instalación. Y debes respetar las
!href cmd=help&special_parm=dependencies dependencias
entre los recursos. La regla general es no restaurar
registros de actividad de los participantes y no restaurar los recursos didácticos
interactivo (documentos, ejercicios, hojas de trabajo y exámenes)
de diferentes fuentes.
</li>
</ul>
